version: 2

before:
  hooks:
    # Ensure dependencies are up to date
    - go mod tidy
    - go mod download

builds:
  # Server binary
  - id: innominatus
    main: ./cmd/server/main.go
    binary: innominatus
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

  # CLI binary
  - id: innominatus-ctl
    main: ./cmd/cli/main.go
    binary: innominatus-ctl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  # Server archive (Linux only)
  - id: server-archive
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}-server_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    # Only package the server binary (Linux builds)
    builds:
      - innominatus
    files:
      - README.md
      - LICENSE
      - examples/admin-config.yaml
      - examples/goldenpaths.yaml
      - workflows/**
      - docs/**

  # CLI archive (all platforms)
  - id: cli-archive
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}-ctl_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    # Only package the CLI binary (all platforms)
    builds:
      - innominatus-ctl
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'typo'
      - 'README'

docker_manifests:
  # Create multi-arch images
  - name_template: "ghcr.io/philipsahli/innominatus:{{ .Version }}"
    image_templates:
      - "ghcr.io/philipsahli/innominatus:{{ .Version }}-amd64"
      - "ghcr.io/philipsahli/innominatus:{{ .Version }}-arm64"

  - name_template: "ghcr.io/philipsahli/innominatus:latest"
    image_templates:
      - "ghcr.io/philipsahli/innominatus:latest-amd64"
      - "ghcr.io/philipsahli/innominatus:latest-arm64"

dockers:
  # AMD64 image
  - image_templates:
      - "ghcr.io/philipsahli/innominatus:{{ .Version }}-amd64"
      - "ghcr.io/philipsahli/innominatus:latest-amd64"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
    goarch: amd64
    extra_files:
      - cmd/
      - internal/
      - pkg/
      - migrations/
      - web-ui/
      - examples/
      - workflows/
      - docs/
      - go.mod
      - go.sum

  # ARM64 image
  - image_templates:
      - "ghcr.io/philipsahli/innominatus:{{ .Version }}-arm64"
      - "ghcr.io/philipsahli/innominatus:latest-arm64"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
    goarch: arm64
    extra_files:
      - cmd/
      - internal/
      - pkg/
      - migrations/
      - web-ui/
      - examples/
      - workflows/
      - docs/
      - go.mod
      - go.sum

release:
  github:
    owner: philipsahli
    name: innominatus
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## innominatus {{ .Version }}

    Score-based platform orchestration component

    ### Installation

    **Quick Install (macOS/Linux):**
    ```bash
    # Install both server and CLI
    curl -fsSL https://raw.githubusercontent.com/philipsahli/innominatus/main/install.sh | bash

    # Install CLI only
    curl -fsSL https://raw.githubusercontent.com/philipsahli/innominatus/main/install.sh | bash -s -- --component cli

    # Install specific version
    curl -fsSL https://raw.githubusercontent.com/philipsahli/innominatus/main/install.sh | bash -s -- --version {{ .Version }}
    ```

    **Docker:**
    ```bash
    docker pull ghcr.io/philipsahli/innominatus:{{ .Version }}
    docker run -p 8081:8081 ghcr.io/philipsahli/innominatus:{{ .Version }}
    ```

    **Manual Download:**
    Download the appropriate archive for your platform below.

  footer: |
    ---
    **Full Changelog**: https://github.com/philipsahli/innominatus/compare/{{ .PreviousTag }}...{{ .Tag }}

announce:
  skip: true
