apiVersion: v1
kind: Provider
metadata:
  name: storage-team
  version: 1.0.0
  category: storage
  description: Object storage provisioners for S3-compatible storage (Minio)

compatibility:
  minCoreVersion: 1.0.0
  maxCoreVersion: 2.0.0

workflows:
  - name: provision-s3-bucket
    file: ./workflows/provision-s3-bucket.yaml
    description: Create S3 bucket on Minio with access credentials
    category: provisioner
    version: 1.0.0
    tags: [s3, storage, minio, object-storage]
