apiVersion: innominatus.io/v1alpha1
kind: Workflow
metadata:
  name: provision-keycloak-group
  description: Create Keycloak group/team for identity and access management

parameters:
  - name: group_name
    type: string
    required: true
    description: Name of the group/team to create

  - name: realm
    type: string
    required: false
    default: "demo-realm"
    description: Keycloak realm

steps:
  - name: create-group
    type: policy
    config:
      command: |
        #!/bin/bash
        set -e

        echo "👥 Creating Keycloak group: {{ .parameters.group_name }}"

        KEYCLOAK_URL="${KEYCLOAK_URL:-http://keycloak.localtest.me}"
        KEYCLOAK_ADMIN="${KEYCLOAK_ADMIN:-admin}"
        KEYCLOAK_PASSWORD="${KEYCLOAK_PASSWORD:-adminpassword}"
        REALM="{{ .parameters.realm }}"
        GROUP_NAME="{{ .parameters.group_name }}"
        GROUP_PATH="/$GROUP_NAME"

        # Get admin access token
        echo "🔐 Authenticating with Keycloak..."
        TOKEN_RESPONSE=$(curl -s -X POST \
          "$KEYCLOAK_URL/realms/master/protocol/openid-connect/token" \
          -H "Content-Type: application/x-www-form-urlencoded" \
          -d "username=$KEYCLOAK_ADMIN" \
          -d "password=$KEYCLOAK_PASSWORD" \
          -d "grant_type=password" \
          -d "client_id=admin-cli")

        ACCESS_TOKEN=$(echo "$TOKEN_RESPONSE" | grep -o '"access_token":"[^"]*"' | cut -d'"' -f4)

        if [ -z "$ACCESS_TOKEN" ]; then
          echo "❌ Failed to authenticate with Keycloak"
          echo "Response: $TOKEN_RESPONSE"
          exit 1
        fi

        echo "✅ Authentication successful"

        # Check if group already exists
        echo "🔍 Checking if group '$GROUP_NAME' exists..."
        GROUPS_RESPONSE=$(curl -s -w "\nHTTP_CODE:%{http_code}" \
          -H "Authorization: Bearer $ACCESS_TOKEN" \
          "$KEYCLOAK_URL/admin/realms/$REALM/groups")

        HTTP_CODE=$(echo "$GROUPS_RESPONSE" | grep "HTTP_CODE:" | cut -d: -f2)
        GROUPS_BODY=$(echo "$GROUPS_RESPONSE" | sed '/HTTP_CODE:/d')

        if [ "$HTTP_CODE" != "200" ]; then
          echo "❌ Failed to query groups (HTTP $HTTP_CODE)"
          echo "Response: $GROUPS_BODY"
          exit 1
        fi

        # Extract group ID if exists
        GROUP_EXISTS=$(echo "$GROUPS_BODY" | grep -o "\"name\":\"$GROUP_NAME\"" || echo "")

        if [ -n "$GROUP_EXISTS" ]; then
          echo "✅ Group '$GROUP_NAME' already exists"
          GROUP_ID=$(echo "$GROUPS_BODY" | grep -B5 "\"name\":\"$GROUP_NAME\"" | grep -o '"id":"[^"]*"' | head -1 | cut -d'"' -f4)

          echo "   Group ID: $GROUP_ID"
          echo "   Group Path: $GROUP_PATH"

          # Output existing group details
          cat <<EOF
        {
          "group_id": "$GROUP_ID",
          "group_name": "$GROUP_NAME",
          "group_path": "$GROUP_PATH",
          "realm": "$REALM",
          "status": "exists"
        }
        EOF
          exit 0
        fi

        # Create group
        echo "📝 Creating new group..."
        CREATE_RESPONSE=$(curl -s -w "\nHTTP_CODE:%{http_code}" \
          -H "Authorization: Bearer $ACCESS_TOKEN" \
          -H "Content-Type: application/json" \
          -X POST \
          -d "{
            \"name\": \"$GROUP_NAME\",
            \"path\": \"$GROUP_PATH\"
          }" \
          "$KEYCLOAK_URL/admin/realms/$REALM/groups")

        HTTP_CODE=$(echo "$CREATE_RESPONSE" | grep "HTTP_CODE:" | cut -d: -f2)
        RESPONSE_BODY=$(echo "$CREATE_RESPONSE" | sed '/HTTP_CODE:/d')

        if [ "$HTTP_CODE" = "201" ]; then
          echo "✅ Group created successfully"

          # Fetch the created group to get its ID
          sleep 1
          VERIFY_RESPONSE=$(curl -s \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            "$KEYCLOAK_URL/admin/realms/$REALM/groups")

          GROUP_ID=$(echo "$VERIFY_RESPONSE" | grep -B5 "\"name\":\"$GROUP_NAME\"" | grep -o '"id":"[^"]*"' | head -1 | cut -d'"' -f4)

          echo "   Group ID: $GROUP_ID"
          echo "   Group Path: $GROUP_PATH"
          echo "   Realm: $REALM"

          # Output group details
          cat <<EOF
        {
          "group_id": "$GROUP_ID",
          "group_name": "$GROUP_NAME",
          "group_path": "$GROUP_PATH",
          "realm": "$REALM",
          "status": "created"
        }
        EOF
        else
          echo "❌ Failed to create group (HTTP $HTTP_CODE)"
          echo "Response: $RESPONSE_BODY"
          exit 1
        fi

outputs:
  group_name: "{{ .parameters.group_name }}"
  group_path: "/{{ .parameters.group_name }}"
  realm: "{{ .parameters.realm }}"
  group_id: "{{ .steps.create-group.output.group_id }}"
  status: "{{ .steps.create-group.output.status }}"
