apiVersion: v1
kind: Provider
metadata:
  name: builtin
  version: 1.0.0
  category: infrastructure
  description: Built-in workflows for platform engineering

compatibility:
  minCoreVersion: 1.0.0
  maxCoreVersion: 2.0.0

capabilities:
  resourceTypes: []
